# This rule is not used by the project forgejo-act-runner-controller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the forgejo.actions.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: forgejo-act-runner-controller
    app.kubernetes.io/managed-by: kustomize
  name: actrunner-editor-role
rules:
- apiGroups:
  - forgejo.actions.io
  resources:
  - actrunners
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - forgejo.actions.io
  resources:
  - actrunners/status
  verbs:
  - get
