# This rule is not used by the project forgejo-act-runner-controller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to forgejo.actions.io.github.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: forgejo-act-runner-controller
    app.kubernetes.io/managed-by: kustomize
  name: actrunner-viewer-role
rules:
- apiGroups:
  - forgejo.actions.io.github.com
  resources:
  - actrunners
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - forgejo.actions.io.github.com
  resources:
  - actrunners/status
  verbs:
  - get
