# This rule is not used by the project forgejo-act-runner-controller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over forgejo.actions.io.github.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: forgejo-act-runner-controller
    app.kubernetes.io/managed-by: kustomize
  name: actrunner-admin-role
rules:
- apiGroups:
  - forgejo.actions.io.github.com
  resources:
  - actrunners
  verbs:
  - '*'
- apiGroups:
  - forgejo.actions.io.github.com
  resources:
  - actrunners/status
  verbs:
  - get
