apiVersion: forgejo.actions.io.github.com/v1alpha1
kind: RunnerDeployment
metadata:
  labels:
    app.kubernetes.io/name: forgejo-act-runner-controller
    app.kubernetes.io/managed-by: kustomize
  name: runnerdeployment-sample
spec:
  # TODO(user): Add fields here
